
theme: jekyll-theme-slate
title: Myelofon
google_analytics: UA-99577378-1
github:
  repository_url: https://github.com/sudachen/Myelofon
gems:
  - jekyll-feed
  - jekyll-theme-slate
exclude:
  - Gemfile
  - Gemfile.lock


